//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 5/27/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
// 5/27/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "Util1/Tester/TestSuite.h"

#include "Tester/TestSuite.h"
#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "Util1/Tester/WaitTester.h"

//
// Default constructor.
// Code automatically generated by TorturerGen
//
AosUtil1TestSuite::AosUtil1TestSuite()
{
}


//
// Destructor.
// Code automatically generated by TorturerGen
//
AosUtil1TestSuite::~AosUtil1TestSuite()
{
}


//
// Code automatically generated by TorturerGen
//
OmnTestSuitePtr
AosUtil1TestSuite::getSuite()
{
    OmnTestSuitePtr suite = OmnNew OmnTestSuite("Util1TestSuite", "");
    // 
    // Add all the testers
    // 
    suite->addTestPkg(OmnNew AosWaitTester());

    return suite;
}

