//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 3/19/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "UserMgmt/Tester/UserTester.h"

#include "Debug/Debug.h"
#include "Tester/Test.h"
#include "Tester/TestMgr.h"
#include "Tracer/Tracer.h"
#include "UserMgmt/User.h"


AosUserTesterTester::AosUserTesterTester()
{
    mTries = 10000;
    mName = "AosUserTesterTester";
}


AosUserTesterTester::~AosUserTesterTester()
{
}


bool
AosUserTesterTester::start()
{
    basicTest();
    return true;
}


bool
AosUserTesterTester::basicTest()
{
	AosUser user(10);

	OmnTCBool(true, user.removeAllFromDb()) << endtc;

	user.setUserName("cding");
	user.setFirstName("chen");
	user.setLastName("ding");
	user.setEmail("cding@packetengineering.com");
	user.setOfficePhone("469.951.9648");
	user.setHomePhone("972.618.9648");
	user.setDescription("This is a test");
	user.setStatus(AosUser::eActive);
	OmnTCBool(true, user.saveToDb()) << endtc;

	OmnTCBool(true, user.removeFromDb()) << endtc;
    return true;
}


