//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 5/18/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#ifndef Aos_TorturerGen_Tester_AosFuncTest_h
#define Aos_TorturerGen_Tester_AosFuncTest_h

#include "Debug/Debug.h"
#include "Tester/TestPkg.h"
#include "Util/Ptrs.h"



class AosFuncTest : public OmnTestPkg
{
private:
    int              mBasicTestRepeat;
    AosGenTablePtr   mTable;

public:
    AosFuncTest();
    ~AosFuncTest();

    virtual bool     start();


private:
    bool basicTest(const u32 repeat, const AosGenTablePtr &table);
};
#endif

