//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 5/18/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
// 5/18/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "TorturerGen/Tester/TestSuite.h"

#include "Tester/TestSuite.h"
#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "TorturerGen/Tester/FuncTest.h"

//
// Default constructor.
// Code automatically generated by TorturerGen
//
AosFuncTorturerTestSuite::AosFuncTorturerTestSuite()
{
}


//
// Destructor.
// Code automatically generated by TorturerGen
//
AosFuncTorturerTestSuite::~AosFuncTorturerTestSuite()
{
}


//
// Code automatically generated by TorturerGen
//
OmnTestSuitePtr
AosFuncTorturerTestSuite::getSuite()
{
    OmnTestSuitePtr suite = OmnNew OmnTestSuite("FuncTorturerTestSuite", "");
    // 
    // Add all the testers
    // 
    suite->addTestPkg(OmnNew AosFuncTest());

    return suite;
}

