////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
//
// Modification History:
// 01/23/2011	Created by Chen Ding
////////////////////////////////////////////////////////////////////////////
#ifndef Aos_SeReqProc_ReqidNames_h
#define Aos_SeReqProc_ReqidNames_h

#define AOSREQIDNAME_GET_ACCRCD				"arcd_get"
#define AOSREQIDNAME_ADD_FRIEND				"addfriend"
#define AOSREQIDNAME_ADD_FOLLOWER			"addfollower"
#define AOSREQIDNAME_ADD_MEMBER				"addmember"
#define AOSREQIDNAME_ADDSCHEDULE			"addschedule"
#define AOSREQIDNAME_ALLOWANCE				"allowancetask"
#define AOSREQIDNAME_APPLY_FRIEND			"applyfriend"
#define AOSREQIDNAME_BATCHDELETE			"batchdelete"
#define AOSREQIDNAME_APPEND_MANUALORDER		"crtcmol"
#define AOSREQIDNAME_CHECK_CLOUDID			"checkcid"
#define AOSREQIDNAME_CHECKLOGIN				"checklogin"
#define AOSREQIDNAME_COMPOSER_TN			"composerTN"
#define AOSREQIDNAME_COUNTER				"counter"
#define AOSREQIDNAME_CREATE_ACCESSRECORD	"create_arcd"
#define AOSREQIDNAME_CREATE_INBOX           "create_inbox"
#define AOSREQIDNAME_CREATE_MSG    			"create_msg"
#define AOSREQIDNAME_CREATE_ORDER			"create_order"
#define AOSREQIDNAME_CREATE_SUPER_USER		"create_super_user"
#define AOSREQIDNAME_CREATETALKGROUP		"createtalkgroup"
#define AOSREQIDNAME_CREATE_USER			"create_user"
#define AOSREQIDNAME_CREATE_USERDOMAIN      "createuserdomain"
#define AOSREQIDNAME_CREATE_MSGCONTAINER    "create_msgcontainer"
#define AOSREQIDNAME_CREATEOBJ_BYTPL		"crtobjbytpl"
#define AOSREQIDNAME_CONVERTSQLDATA			"convertsqldata"
#define AOSREQIDNAME_DOWNLOAD				"download"
#define AOSREQIDNAME_DELETE_MSGCONTAINER    "delete_msgcontainer"
#define AOSREQIDNAME_DELETE_MSG			    "delete_msg"
#define AOSREQIDNAME_DENY_FRIEND			"denyfriend"
#define AOSREQIDNAME_EXPORTDATA             "exportdata"
#define AOSREQIDNAME_FORUM					"forum"
#define AOSREQIDNAME_FINISH_IMSESSION		"finishimsession"
#define AOSREQIDNAME_GET_ONLINE_USER		"getusers"
#define AOSREQIDNAME_GETONLINE_FRIEND		"getonlinefriend"
#define AOSREQIDNAME_GET_DOMAIN				"getdomain"
#define AOSREQIDNAME_GET_NEWID				"get_newid"
#define AOSREQIDNAME_GET_CLOUDID			"getcid"
#define AOSREQIDNAME_INCREMENT_ATTR			"incattr"
#define AOSREQIDNAME_INVITE_FRIEND          "invitefriend"
#define AOSREQIDNAME_USER_LOGOUT			"logout"
#define AOSREQIDNAME_MODIFYOBJ_BYTPL		"modobjbyvw"
#define AOSREQIDNAME_MOVE_MSG               "move_msg"
#define AOSREQIDNAME_MOVE_MANUAL_ORDER		"mvcmol"
#define AOSREQIDNAME_MODIFY_ATTR			"modattr"
#define AOSREQIDNAME_PROCONLINESTATUS		"proconlinestatus"
#define AOSREQIDNAME_REG_HOOK				"reghook"
#define AOSREQIDNAME_REMOVE_FRIEND			"removefriend"
#define AOSREQIDNAME_REMOVE_FRIENDGROUP		"removefriendgroup"
#define AOSREQIDNAME_REMOVE_FOLLOWER		"removefollower"
#define AOSREQIDNAME_REMOVE_MBLOGMSG		"removemblogmsg"
#define AOSREQIDNAME_REMOVE_TALKGROUP		"removetalkgroup"
#define AOSREQIDNAME_REMOVE_MANUAL_ORDER    "rmcmol"
#define AOSREQIDNAME_SEND_MBLOGMSG			"sendmblogmsg"
#define AOSREQIDNAME_SWAP_MANUAL_ORDER      "swpcmol"
#define AOSREQIDNAME_SEND_INSTANTMSG        "sendinstantmsg"
///////////////////////////////////////////////////////////
#define AOSREQIDNAME_ADDSENDER				"addsender"
#define AOSREQIDNAME_REMOVESENDER			"removesender"
#define AOSREQIDNAME_ADDFOLLOWERTOACCT		"addfollowertoacct"
#define AOSREQIDNAME_RMFOLLOWERFROMACCT		"rmfollowerfromacct"
#define AOSREQIDNAME_SENDMSGBYACCOUNT		"sendmsgbyacct"
#define AOSREQIDNAME_SENDMSGTOUSER			"sendmsgtouser"
//////////////////////////////////////////////////////////////////
#define AOSREQIDNAME_MODIFY_ACCRCD			"arcd_mod"
#define AOSREQIDNAME_GET_LANGUAGE           "get_language"
#define AOSREQIDNAME_COPYDOCS_FROM_CTNR     "copydocsfromctnr"
#define AOSREQIDNAME_SENDSHORTMSG			"sdshm"
#define AOSREQIDNAME_ALIPAY					"alipay"
#define AOSREQIDNAME_CREATECOMMENT			"crtcmt"
#define AOSREQIDNAME_LOGINTOESVR			"lgesvr"
#define AOSREQIDNAME_SHMCONFIRM				"shmcfrm"
#define AOSREQIDNAME_VOTE					"vote"
#define AOSREQIDNAME_GETUSERDOCBYCLD		"getuserdocbycloudid"
#define AOSREQIDNAME_CREATELOGENTRY			"crtlog"
#define AOSREQIDNAME_PUBLISH                "publish"
#define AOSREQIDNAME_RESOLVEURI             "resolve_uri"
#define AOSREQIDNAME_RESOLVEURL             "resolve_url"
#define AOSREQIDNAME_REBUILDVERSION         "rebuildver"
#define AOSREQIDNAME_REBUILDLOG             "rebuildlog"
#define AOSREQIDNAME_GETSERVERTIME          "servertime"
#define AOSREQIDNAME_THUMBNAIL              "thumbnail"
#define AOSREQIDNAME_UPLOADIMGREQ           "uploadimg"
#define AOSREQIDNAME_UPLOADFILEREQ          "uploadfile"
#define AOSREQIDNAME_CREATEOBJ              "createcobj"
#define AOSREQIDNAME_CREATELOG              "createlog"
#define AOSREQIDNAME_DATASYNC               "datasync"
#define AOSREQIDNAME_LOGIN                  "login"
#define AOSREQIDNAME_SENDMAIL               "sendmail"
#define AOSREQIDNAME_MODIFYNODE				"modifynode"
#define AOSREQIDNAME_RETRIEVELOG            "reclog"
#define AOSREQIDNAME_ADDVERSION             "addver"
#define AOSREQIDNAME_REMOVE_MEMBER			"removemember"
#define AOSREQIDNAME_STOP_SERVER			"stop_server"
#define AOSREQIDNAME_ONE_KEY_COPY			"onekeycopy"
#define AOSREQIDNAME_RECENT_VPD				"recentvpd"
#define AOSREQIDNAME_RESUME_REQ				"resume_req"
#define AOSREQIDNAME_RUN_SMARTDOC			"sdocrun"
#define AOSREQIDNAME_SCAN_OBJID				"scanobjid"
#define AOSREQIDNAME_SMART_REPLY			"smart_reply"
#define AOSREQIDNAME_CHECKUNIQUE			"checkunique"
#define AOSREQIDNAME_NOTIFYFRIEND			"notifyfriend"
#define AOSREQIDNAME_MODIFYPASSWORD			"modifypassword"
#define AOSREQIDNAME_INCREMENTINLINESEARCH	"incrementInlineSearch"
#define AOSREQIDNAME_CREATE_OPRARD			"create_oprard"
#define AOSREQIDNAME_GET_USER_OPRARD		"get_usroprard"
#define AOSREQIDNAME_DOCLOCKREQ				"doclock"
#define AOSREQIDNAME_PROCECG				"procecg"
#define AOSREQIDNAME_CREATEECGIMG			"create_ecg_img"
#define AOSREQIDNAME_CONTEC_ECG_PROC		"contececgproc"
#define AOSREQIDNAME_UPDATE_LOGIN_INFO		"update_loginfo"
#define AOSREQIDNAME_GETSERVERINFO			"getserverinfo"
#define AOSREQIDNAME_RUNCOMMAND				"runcommand"
#define AOSREQIDNAME_SENDTOMSGSERVICE       "sendtomsgservice"
#define AOSREQIDNAME_CHECKIILENTRY			"checkiilentry"		// Ken Lee, 2013/08/20
#define AOSREQIDNAME_RUN_JQL				"runjql"
#define AOSREQIDNAME_RUN_INDEXMGR			"run_indexmgr"
#define AOSREQIDNAME_JQLLOGIN				"jql_login"
#define AOSREQIDNAME_RUNSQL					"runsql"

#endif

