/*generated by gencode.py
 *author: bill xia
 */

#include <stdio.h>

#include "aosApi.h"
int main()
{
    char result[10240];
    int ret = 0;
    int len = 10240;
    int total_case = 0;
    int fail_case = 0;

    ret = aos_api_pppoe_start();
    if (ret != 0) {
        printf("caseId:1	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_stop();
    if (ret != 0) {
        printf("caseId:2	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_retrieve_config(result, &len);
    if (ret != 0) {
        printf("caseId:3	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_save_config();
    if (ret != 0) {
        printf("caseId:4	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_clear_config();
    if (ret != 0) {
        printf("caseId:5	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_username_set("adlstest");
    if (ret != 0) {
        printf("caseId:6	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_password_set("adlpasswd");
    if (ret != 0) {
        printf("caseId:7	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_pppoe_dns_set("192.168.0.1", "172.22.0.1");
    if (ret != 0) {
        printf("caseId:8	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;

    printf("total case: %d\n fail case:%d", total_case, fail_case);
    return 0;
}
