////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility.
//
// Modification History:
// 7/18/2007 : Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "AutoTorturing/src/QoS/InstGen_qos_macrule.h"

#include "CliTorturer/CliTorturer.h"
#include "Tester/TestMgr.h"
#include "Torturer/Parm.h"
#include "Torturer/ParmIncls.h"
#include "Torturer/ParmInstGen.h"
#include "Torturer/ParmInt.h"
#include "Torturer/ParmStr.h"
#include "Util/DynArray.h"
#include "Util/String.h"
#include "Util/RCObject.h"
#include "Util/RCObjImp.h"
#include "XmlParser/XmlItem.h"



qos_macrule_InstGen::qos_macrule_InstGen(const OmnString &name)
:
AosParmInstGen(name)
{
}

qos_macrule_InstGen::~qos_macrule_InstGen()
{
}


bool
qos_macrule_InstGen::nextStr(OmnString &value,
                 		const AosGenTablePtr &data,
				        const AosGenRecordPtr &record,
						bool &isCorrect,
						const bool correctOnly,
						const bool selectFromRecord,
						AosParmReturnCode &rcode,
						OmnString &errmsg)
{
	if (!mInstGen)
	{
		OmnAlarm << "mInstGen is null" << enderr;
		return false;
	}

    struct qos_macrule* inst = OmnNew qos_macrule;
    if (mInstance) OmnDelete mInstance; 
    mInstance = inst;
    qos_macrule_InstGenPtr ptr = (qos_macrule_InstGen *) mInstGen.getPtr();

	return ptr->nextPtr(inst, data, record, isCorrect, correctOnly, 
			selectFromRecord, rcode, errmsg);
}


bool
qos_macrule_InstGen::nextPtr(
				 struct qos_macrule* inst,
				 const AosGenTablePtr &data,
				 const AosGenRecordPtr &record,
				 bool &isCorrect,
				 const bool correctOnly,
				 const bool selectFromRecord,
				 AosParmReturnCode &rcode,
				 OmnString &errmsg)
{
	    bool __correct;
	isCorrect = true;

	
    OmnString mMember0;
    if (!mParmGens[0]->nextStr(mMember0, data, record, __correct, correctOnly, selectFromRecord, rcode, errmsg))
    {
        OmnAlarm << "Failed to generate member: "
            << mParmGens[0]->getName() << enderr;
        isCorrect = false;
        return 0;
    }
    isCorrect = isCorrect && __correct;

    int mMember1;
    if (!mParmGens[1]->nextInt(mMember1, data, record, __correct, correctOnly, selectFromRecord, rcode, errmsg))
    {
        OmnAlarm << "Failed to generate member: "
            << mParmGens[1]->getName() << enderr;
        isCorrect = false;
        return 0;
    }
    isCorrect = isCorrect && __correct;


	strncpy(inst->mac, mMember0, 31);
		inst->priority = mMember1;
	return true;
}


bool
qos_macrule_InstGen::nextInst(qos_macrule_InstGen &inst,
				  const AosGenTablePtr &data,
				 const AosGenRecordPtr &record,
				 bool &isCorrect,
				 const bool correctOnly,
				 const bool selectFromRecord,
				 AosParmReturnCode &rcode,
				 OmnString &errmsg)
{
	    if (!mParmGens[0]->nextStr(mMember0, data, record, isCorrect, correctOnly, selectFromRecord, 
            rcode, errmsg)) 
    {
        OmnAlarm << "Failed to generate member: "
            << mParmGens[0]->getName() << enderr;
        return 0;
    }
    if (!mParmGens[1]->nextInt(mMember1, data, record, isCorrect, correctOnly, selectFromRecord, 
            rcode, errmsg)) 
    {
        OmnAlarm << "Failed to generate member: "
            << mParmGens[1]->getName() << enderr;
        return 0;
    }


	return true;
}


AosParmPtr
qos_macrule_InstGen::createInstance(const OmnXmlItemPtr &def, OmnVList<AosGenTablePtr> &tables)
{
    qos_macrule_InstGenPtr inst = OmnNew qos_macrule_InstGen(getName());
	if (!inst->config(def, "", tables, false))
	{
		OmnAlarm << "Failed to config the object" << enderr;
		return 0;
	}
	
	return inst;         
}


bool
qos_macrule_InstGen::registerInstanceGen(const OmnString &name)
{
	qos_macrule_InstGenPtr inst = OmnNew qos_macrule_InstGen(name);
	if (!AosParmInstGen::registerInstanceGen(inst))
	{
		OmnAlarm << "Failed to register Instance Generator: " 
			<< "qos_macrule_InstGen" << enderr;
		return false;
	}

	return true;
}


bool
qos_macrule_InstGen::getCrtValue(AosParmInstGenPtr &value) const
{
	value = mLastInstGen;
	return true;
}


bool 	
qos_macrule_InstGen::getCrtValueAsArg(OmnString &value) const
{
	value = "inst";
	return true;
}


AosParmInstGenPtr 
qos_macrule_InstGen::clone() const
{
	qos_macrule_InstGenPtr ptr = OmnNew qos_macrule_InstGen;	
	copyData(ptr.getPtr());
	return ptr.getPtr();
}

