create table group_obj_dm (
	tablename		varchar(64) not null primary key,
	name			varchar(64),
	tagging			text,
	description		text,
	key_fields		text,
	tagging_fname	text,
	name_fname		text,
	desc_fname		text,
	max_limit		int,
	no_delete		varchar(10) default "false",
	readonly		varchar(10) default "false",
	log				varchar(10) default "false",
	stat			varchar(10) default "false",
	obj_listing		varchar(10),
	indexed_fields	text,
	translators		text,
	archive			varchar(10),
	create_time		datetime,
	mod_time		datetime,
	read_lock		varchar(10),
	rl_user			varchar(32),
	rl_time			datetime,
	write_lock		varchar(10),
	wl_user			varchar(32),
	wl_time			datetime,
	newobj_lock		varchar(10),
	nol_user		varchar(32),
	nol_time		datetime
); 
