/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package zykie.jimoapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JmoDataType implements org.apache.thrift.TEnum {
  Int64(0),
  STRING(1);

  private final int value;

  private JmoDataType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JmoDataType findByValue(int value) { 
    switch (value) {
      case 0:
        return Int64;
      case 1:
        return STRING;
      default:
        return null;
    }
  }
}
