//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 05/06/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "RandomValueGen/Tester/IntRVGTester.h"

#include "RandomValueGen/Ptrs.h"
#include "RandomValueGen/RVGInt.h"
#include "RandomValueGen/Util.h"
#include "RandomValueGen/Tester/Util.h"
#include "Debug/Debug.h"
#include "Tester/Test.h"
#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "Util/GenTable.h"
#include "Util/GenRecord.h"
#include "XmlParser/XmlItem.h"


AosIntRVGTester::AosIntRVGTester()
{
    mName = "AosIntRVGTester";
}


AosIntRVGTester::~AosIntRVGTester()
{
}


bool
AosIntRVGTester::start()
{
	createData();
//    testNewKey();
	stressTest(1000000 * 100);
    return true;
}


const OmnString sgTableWithKeyDef = 
"<TableDef>"
	"<MaxEntries>100</MaxEntries>"
	"<KeyFields>app_id</KeyFields>"
	"<Fields>"
		"<Field>"
			"<Type>int</Type>"
			"<Name>app_id</Name>"
		"</Field>"
	"</Fields>"
"</TableDef>";

const OmnString sgTableNoKeyDef = 
"<TableDef>"
	"<MaxEntries>100</MaxEntries>"
	"<Fields>"
		"<Field>"
			"<Type>int</Type>"
			"<Name>app_id</Name>"
		"</Field>"
	"</Fields>"
"</TableDef>";

bool
AosIntRVGTester::createData()
{
	// 
	// Create RVGs 
	//
	/*
	OmnXmlItemPtr item = OmnNew OmnXmlItem(sgTableWithKeyDef);
	mTableWithKey = OmnNew AosGenTable(item);

	item = OmnNew OmnXmlItem(sgTableNoKeyDef);
	mTableNoKey = OmnNew AosGenTable(item);

	OmnDynArray<AosGenTablePtr> depTables;
	OmnDynArray<OmnString> fieldnames;

	OmnString validValues = "[10, 100, 30], [1000, 2000, 50]";
	OmnString invalidValues = "[-100, 9, 20], [101, 199, 40], [201, 999, 70]";
	mParmNew = OmnNew AosRVGInt("IntTester", "app_id", eAosRVGKeyType_SingleKeyNew, 
					validValues, invalidValues, -1, false, mTableWithKey, 
					depTables, fieldnames);
	mParmExist = OmnNew AosRVGInt("IntTester", "app_id", eAosRVGKeyType_SingleKeyExist, 
					validValues, invalidValues, -1, false, mTableWithKey, 
					depTables, fieldnames);
	mParmNotKey = OmnNew AosRVGInt("IntTester", "app_id", eAosRVGKeyType_NoKey, 
					validValues, invalidValues, -1, false, mTableNoKey, 
					depTables, fieldnames);

	*/

	return true;
}

