//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 3/4/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
// 3/4/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "RandomValueGen/Tester/TestSuite.h"

#include "Tester/TestSuite.h"
#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "RandomValueGen/Tester/NetmaskRVGTester.h"
#include "RandomValueGen/Tester/IntRVGTester.h"
#include "RandomValueGen/Tester/StrRVGTester.h"
#include "RandomValueGen/Tester/StrEnumRVGTester.h"

//
// Default constructor.
// Code automatically generated by TorturerGen
//
AosTorturerTestSuite::AosTorturerTestSuite()
{
}


//
// Destructor.
// Code automatically generated by TorturerGen
//
AosTorturerTestSuite::~AosTorturerTestSuite()
{
}


//
// Code automatically generated by TorturerGen
//
OmnTestSuitePtr
AosTorturerTestSuite::getSuite()
{
    OmnTestSuitePtr suite = OmnNew OmnTestSuite("TorturerTestSuite", "Torturer");

//	suite->addTestPkg(OmnNew AosNetmaskRVGTester());
//	suite->addTestPkg(OmnNew AosIntRVGTester());
//	suite->addTestPkg(OmnNew AosStrRVGTester());
	suite->addTestPkg(OmnNew AosStrEnumRVGTester());

    return suite;
}

