/*generated by gencode.py
 *author: bill xia
 *modify history: Ricky Chen 2007.4.3
 */

#include "aosApi.h"
#include <stdio.h>
#include <iostream.h>

int main(int argc,char ** argv)
{
	char result[10240];
	int ret = 0;
	int len = 10240;
	int total_case = 0;
	int fail_case = 0;
	int index=1;
	int count=0;
	int maxruntime=2;
	FILE *fp=NULL; 

	while(index<argc)
	{
		if(strcmp(argv[index],"-t")==0)
		{
			maxruntime=atoi(argv[++index]);
			index++;
			continue;
		}
		if(strcmp(argv[index],"-h")==0)
		{
			cout<<"----------------------helps for usage------------------------------------------"<<endl;
			cout<<"1 usage: ./dmztester [-t [count]]"<<endl;
			cout<<""<<endl;
			cout<<"2 the parameter [-t [count]] is optinal,it control the total run count of this application ."<<endl;
			cout<<" it's default value is 2 ,if it need to set it .it need a number of 2's times(eg: 2,4,6,...)  "<<endl;
			cout<<""<<endl;
			cout<<"3 the result will be added to the files dmzresult1 and dmzresult2 in the current directory at the mean"<<endl;
			cout<<"  time,and this two result file's content should be the same"<<endl;
			cout<<""<<endl;
			cout<<"4 exmaple: './dmztester -t 10 ' or ' ./dmztester '"<<endl;
			cout<<""<<endl;
			exit(0);
		}
	}


	while(count<maxruntime)
	{
		printf("================================ Now run the %d time=========================================\n",count);
		printf("==============================================================================================\n");

		if(count%2==0)
		{
			fp=fopen("dmzresult1","a+");
		}
		else
		{
			fp=fopen("dmzresult2","a+");
		}  

		cout<<"============================== dnsmasq add section ==================================================\n"<<endl;

		ret = aos_dmz_clear_config();
		if (ret != 0) {
			printf("caseId:6	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz clear config   ret= "<<ret<<endl;
		fprintf(fp,"dmz clear config ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_dmz_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz show config   ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"dmz show config ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_dmz_add_machine("m1", "192.168.0.3", "172.22.0.113");
		if (ret != 0) {
			printf("caseId:2	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz set add machine   ret= "<<ret<<endl;
		fprintf(fp,"dmz add machine  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_dmz_add_machine("m2", "192.168.0.4", "172.22.0.114");
		if (ret != 0) {
			printf("caseId:3	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz set add machine   ret= "<<ret<<endl;
		fprintf(fp,"dmz add machine  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_dmz_set_status(1);
		if (ret != 0) {
			printf("caseId:1	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz set status   ret= "<<ret<<endl;
		fprintf(fp,"dmz set status ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		len = 10240;
		ret = aos_dmz_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz show config   ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"dmz show config ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_dmz_save_config();
		if (ret != 0) {
			printf("caseId:7	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz save config   ret= "<<ret<<endl;
		fprintf(fp,"dmz save config ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		cout<<"============================== dnsmasq del section ==================================================\n"<<endl;

		ret = aos_dmz_del_machine("m1");
		if (ret != 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz del machine   ret= "<<ret<<endl;
		fprintf(fp,"dmz del machine ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_dmz_del_machine("m2");
		if (ret != 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz del machine   ret= "<<ret<<endl;
		fprintf(fp,"dmz del machine ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		len = 10240;
		ret = aos_dmz_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz show config   ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"dmz show config ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_dmz_save_config();
		if (ret != 0) {
			printf("caseId:7	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz save config   ret= "<<ret<<endl;
		fprintf(fp,"dmz save config ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_dmz_clear_config();
		if (ret != 0) {
			printf("caseId:6	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz clear config   ret= "<<ret<<endl;
		fprintf(fp,"dmz clear config ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		cout<<"============================== dnsmasq wrong inpurs section ==================================================\n"<<endl;

		ret = aos_dmz_add_machine("m2", "192.168.0.4", "172..22.0.114");
		if (ret == 0) {
			printf("caseId:3	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz set add machine  WRONG ret= "<<ret<<endl;
		fprintf(fp,"dmz add machine  WRONG ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_dmz_del_machine("m233");
		if (ret == 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz del machine   WRONG ret= "<<ret<<endl;
		fprintf(fp,"dmz del machine WRONG ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		len = 10240;
		ret = aos_dmz_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"dmz show config   ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"dmz show config ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		//not use
		/*
		   ret = aos_dmz_load_config();
		   if (ret != 0) {
		   printf("caseId:8	ret = %d	Error\n", ret);
		   fail_case++;
		   }
		   total_case++;
		   */
		fclose(fp);

		count++;
	}

	cout<<"=================================== DMZ APIS TEST RESULTS SUMMARY===================="<<endl;
	printf("the run total count is: %d\n ",count);
	printf("total case: %d\n ", total_case );
	printf("fail case: %d \n",  fail_case);
	//  printf(" the differdence between the result files is: ", system(" diff dmzresult1 dmzresult2"));
	cout<<""<<endl;
	cout<<"======================================================================================="<<endl;
	return 0;
}
