/*generated by gencode.py
 *author: bill xia
 */

#include <stdio.h>
#include "common.h"

#include "SystemTime.h"
int main()
{
    char result[10240];
    int ret = 0;
    int len = 10240;
    int total_case = 0;
    int fail_case = 0;

    ret = aos_api_system_time_set(12 , 12, 12);
    if (ret != 0) {
        printf("caseId:1	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_system_time_log_show();
    if (ret != 0) {
        printf("caseId:2	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_system_timezone_set(" sd");
    if (ret != 0) {
        printf("caseId:3	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_system_time_fast_set(3600);
    if (ret != 0) {
        printf("caseId:4	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;


    ret = aos_api_system_time_slow_set(3600);
    if (ret != 0) {
        printf("caseId:5	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

len = 10240;

    printf("total case: %d\n fail case:%d\n", total_case, fail_case);
    return 0;
}
