//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// <$$CreationDate> : Created by <$$CreatorName>
//////////////////////////////////////////////////////////////////////////
#include "<$$SourceDirectoryName>/Tester/<$$HeaderFileName>"

#include "CliTorturer/CliTorturer.h"
#include "CliTorturer/ApiTorturerDef.h"
#include "Parms/RVG.h"
#include "Util/GenTable.h"


AosDefineApiTorturer($$ClassName, $$InstancePointer, $$Name)

bool
$$ClassName::runFunc(const bool correctOnly, 
					 const AosCliTorturerPtr &torturer,
					 const OmnTestMgrPtr &testMgr, 
					 const bool cmdCorrect, 
					 OmnString &errmsg, 
					 bool &cmdExecuted)
{
	// 
	// Below are the lines to generate individual arguments
	//
	mTestMgr = testMgr;
	ret = -1;

	$$PARMS

	$$FuncCall

	return true;
}


