//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 05/06/2007 Created by Chen Ding
//////////////////////////////////////////////////////////////////////////
#include "CliTorturer/Tester/ApiTorturerTester.h"

#include "Debug/Debug.h"
#include "CliTorturer/CliTorturer.h"
#include "CliTorturer/CliModuleTorturer.h"
#include "CliTorturer/Tester/CodeGenerated.h"
#include "Random/RandomInteger.h"
#include "Tester/Test.h"
#include "Tester/TestMgr.h"
#include "Torturer/Parm.h"
#include "TorturerConds/Ptrs.h"
#include "TorturerConds/Cond.h"
#include "Util/OmnNew.h"
#include "Util/GenTable.h"
#include "Util/VarList.h"
#include "Util/File.h"
#include "Util/DynArray.h"


AosApiTorturerTester::AosApiTorturerTester()
{
    mName = "AosApiTorturerTester";
}


AosApiTorturerTester::~AosApiTorturerTester()
{
}


bool
AosApiTorturerTester::start()
{
	AosApiTester::registInst();
    AosCliTorturer tort(10, 10, "funcdef.txt", "log.txt", 
		eAosCliTorturerLogType_File, false);
	tort.setTestMgr(mTestMgr);
	tort.start();	
    return true;
}


bool
AosApiTorturerTester::basicTest(const u32 tries)
{
	return true;
}


