//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 05/26/2007 Created by Chen Ding
//////////////////////////////////////////////////////////////////////////
#ifndef Aos_CliTorturer_Tester_CodeGenearted_h
#define Aos_CliTorturer_Tester_CodeGenearted_h

#include "CliTorturer/ApiTorturer.h"
#include "CliTorturer/Tester/Ptrs.h"
#include "Debug/Debug.h"
#include "Tester/TestPkg.h"
#include "Torturer/Ptrs.h"
#include "Util/String.h"
#include "Util/Ptrs.h"


class AosApiTester : public AosApiTorturer, 
					 public OmnTestPkg
{
	OmnDefineRCObject;

private:

public:
	AosApiTester(const OmnString &name);
	virtual ~AosApiTester() {}
	
	virtual AosApiTorturerPtr	createInstance(
					const OmnXmlItemPtr &def,
					const AosCliTorturerPtr &cliTorturer); 
	virtual bool	runFunc(int &ret, const OmnTestMgrPtr &testMgr);

	static bool 	registInst();
};

#endif

