//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 05/26/2007 Created by Chen Ding
//////////////////////////////////////////////////////////////////////////
#include "CliTorturer/Tester/CodeGenerated.h"

#include "CliTorturer/ApiTorturerDef.h"
#include "Torturer/Parm.h"
#include "Util/GenTable.h"

static int my_test_api(const u32 arg1, const OmnString &arg2)
{
	cout << "my_test_api("
		<< arg1 << ", " << arg2 << ")"<< endl;
	return 0;
}

AosDefineApiTorturer(AosApiTester, AosApiTesterPtr, "Test")

bool
AosApiTester::runFunc(int &ret, const OmnTestMgrPtr &testMgr)
{
	// 
	// Below are the lines to generate individual arguments
	//
	mTestMgr = testMgr;
	ret = -1;

	u32 arg1; 		OmnTCTrue_1(mArgs[0]->getCrtValue(arg1), false) << endtc;
	OmnString arg2; OmnTCTrue_1(mArgs[1]->getCrtValue(arg2), false) << endtc;

	ret = my_test_api(arg1, arg2);

	return true;
}


