//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 3/4/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
// 3/4/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "CliTorturer/Tester/TestSuite.h"

#include "CliTorturer/Tester/CliCmdGenericTester.h"
#include "CliTorturer/Tester/ApiTorturerTester.h"
#include "Tester/TestSuite.h"
#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "Util/File.h"
#include "Util/GenTable.h"


OmnFilePtr	AosCliTorturerTestSuite::mLogFile;

//
// Default constructor.
// Code automatically generated by TorturerGen
//
AosCliTorturerTestSuite::AosCliTorturerTestSuite()
{
}


//
// Destructor.
// Code automatically generated by TorturerGen
//
AosCliTorturerTestSuite::~AosCliTorturerTestSuite()
{
}


//
// Code automatically generated by TorturerGen
//
OmnTestSuitePtr
AosCliTorturerTestSuite::getSuite()
{
    OmnTestSuitePtr suite = OmnNew OmnTestSuite("CliTorturerTestSuite", "CLI Torturer");

	// suite->addTestPkg(OmnNew AosCliCmdGenericTester());
	suite->addTestPkg(OmnNew AosApiTorturerTester());

    return suite;
}


bool		
AosCliTorturerTestSuite::openLogfile(const OmnString &filename)
{
	mLogFile = OmnNew OmnFile(filename, OmnFile::eCreate);
	if (!mLogFile->isGood())
	{
		OmnAlarm << "Failed to open the log file: " << filename << enderr;
		mLogFile = 0;
		return false;
	}

	return true;
}


OmnFilePtr	
AosCliTorturerTestSuite::getLogFile() 
{
	return mLogFile;
}


