#!/bin/sh
ulimit -c unlimited

c=1  
while [ $c -le 2 ]  
do  
	server=`ps -ef | grep localserver.exe | grep -v "grep" | awk '{print $2}'`
	if [ "${server}" != "" ]
	then
		echo "exist process!"
	else
		echo "not exist process, ready to start server!"
		echo "move ses_log.txt"
		cd /home/prod/RUN/SERVER 
		mv ses_log.txt ses_log.txt-`date +%Y%m%d-%H%M%S`
		echo "move core"
		cd /home1/data
		mv core core-`date +%Y%m%d-%H%M%S`
		echo start server
		date
		cd /home/prod/RUN/SERVER 
		./runlocal >> ses_log.txt	
	fi
	sleep 10
done  

