/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package zykie.jimoapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JmoQueryOperator implements org.apache.thrift.TEnum {
  GT(0),
  GE(1),
  EQ(2),
  LT(3),
  LE(4),
  NE(5),
  AN(6),
  PREFIX(7),
  LIKE(8),
  DATE(9),
  EPOCH(10),
  GE_LE(11),
  GE_LT(12),
  GT_LE(13),
  GT_Lt(14),
  IN(15),
  DISTINCT(16);

  private final int value;

  private JmoQueryOperator(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JmoQueryOperator findByValue(int value) { 
    switch (value) {
      case 0:
        return GT;
      case 1:
        return GE;
      case 2:
        return EQ;
      case 3:
        return LT;
      case 4:
        return LE;
      case 5:
        return NE;
      case 6:
        return AN;
      case 7:
        return PREFIX;
      case 8:
        return LIKE;
      case 9:
        return DATE;
      case 10:
        return EPOCH;
      case 11:
        return GE_LE;
      case 12:
        return GE_LT;
      case 13:
        return GT_LE;
      case 14:
        return GT_Lt;
      case 15:
        return IN;
      case 16:
        return DISTINCT;
      default:
        return null;
    }
  }
}
