create table se_docheader(
	version 	int,
	docid		bigint,
	seqno		bigint,
	offset		bigint,
	docsize		bigint,
	diskCap		bigint,
	status		char,
	ctime		int,
	mtime		int,
	cntrd		int,
	cntwt		int,
	cntup		int,
	cntdn		int,
	cntcm		int,
	cntrm		int,
	cntcl		int,
	cntlk		int,
	sflag		char,
	vvpd		varchar(64),
	evpd		varchar(64),
	doctype		varchar(32),
	subtype		varchar(32),
	docname		varchar(128),
	tnail		varchar(128),
	appname		varchar(128),
	containers	varchar(1024),
	siteid		varchar(128),
	creator		varchar(32),
	modifier	varchar(32)
);

