#----------------------------------------------------------------------------
#	Makefile for SPNR
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------
#	Local macros
#----------------------------------------------------------------------------
DIRS  = \
		JimoCallSysFunc \
		JimoRandomNumGen \
		JimoRandomStrGen \
		JimoVector

#----------------------------------------------------------------------------
#	Include macros and targets
#----------------------------------------------------------------------------

include	../../makeinclude/wrapper_macros.GNU
include	../../makeinclude/macros.GNU
include	../../makeinclude/rules.common.GNU
include	../../makeinclude/rules.nested.GNU
include	../../makeinclude/rules.nolocal.GNU

