//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// <$$CreationDate> : Created by <$$CreatorName>
//////////////////////////////////////////////////////////////////////////
#include "<$$SourceDirectoryName>/Tester/<$$HeaderFileName>"

#include "Torturer/FuncTorturer.h"
#include "Torturer/FuncModule.h"
#include "Torturer/FuncCmd.h"
#include "Torturer/FuncCmdDef.h"
#include "RVG/RVG.h"
#include "RVG/Table.h"


AosDefineFuncCmd($$ClassName, $$InstancePointer, $$Name)

bool
$$ClassName::runCommand(const bool correctOnly, 
					 const AosTorturerPtr &torturer,
					 const OmnTestMgrPtr &testMgr, 
					 const bool cmdCorrect, 
					 OmnString &errmsg, 
					 bool &cmdExecuted)
{
	// 
	// Below are the lines to generate individual arguments
	//
	mTestMgr = testMgr;
	ret = -1;

	$$PARMS

	$$FuncCall

	return true;
}


