KERNELHOME = /usr/src/linux


install:
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/tcp_timer.c $(KERNELHOME)/net/ipv4/tcp_timer.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/tcp_ipv4.c $(KERNELHOME)/net/ipv4/tcp_ipv4.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/tcp_minisocks.c $(KERNELHOME)/net/ipv4/tcp_minisocks.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/sock.h $(KERNELHOME)/include/net/sock.h
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/syncookies.c $(KERNELHOME)/net/ipv4/syncookies.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/tcp_input.c $(KERNELHOME)/net/ipv4/tcp_input.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/sock.c $(KERNELHOME)/net/core/sock.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/dev.c $(KERNELHOME)/net/core/dev.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/arp.c $(KERNELHOME)/net/ipv4/arp.c
	ln -s -f $(AOSSRC)/KernelHooking/2.6.7/main.c $(KERNELHOME)/init/main.c

