//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 3/19/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
// 3/19/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#include "TransPest/Testers/TestSuite.h"

#include "Tester/TestMgr.h"
#include "Util/OmnNew.h"
#include "TransPest/Testers/TransPestTester.h"

AosTestSuite::AosTestSuite()
{
}


AosTestSuite::~AosTestSuite()
{
}

OmnTestSuitePtr
AosTestSuite::getSuite()
{
    OmnTestSuitePtr suite = OmnNew OmnTestSuite("TestSuite", "");
    // 
    // Add all the testers
    // 

	suite->addTestPkg(OmnNew AosTransPestTester());

    return suite;
}

