/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */

#ifndef AOS_RHC_DMZ_API_H
#define AOS_RHC_DMZ_API_H
#include "aosReturnCode.h"

enum
{
	 eAosRc_DmzAliasExist = 118001,
	 eAosRc_DmzAliasNotExist,
};


/*
 * set dmz status
 */
extern int aos_dmz_set_status(int);
/*
 *  map a public IP into an internal machine
 */
extern int aos_dmz_add_machine(char*, char*, char*);
/*
 * remove a DMZ machine
 */
extern int aos_dmz_del_machine(char*);
/*
 * retrieves the current DMZ configuration
 */
extern int aos_dmz_retrieve_config(char*, int*);
/*
 * clears the current DMZ configuration.
 */
extern int aos_dmz_clear_config();
/*
 * save current DMZ configuration
 */
extern int aos_dmz_save_config();
/*
 * load current DMZ configuration
 */
extern int aos_dmz_load_config();
#endif
