#ifndef AOS_API_PPPOE_H
#define AOS_API_PPPOE_H
#include "aosReturnCode.h"

/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */
/*
 * start pppoe service
 */
extern int aos_api_pppoe_start();
/*
 * stop pppoe servic
 */
extern int aos_api_pppoe_stop();
/*
 * show current configure
 */
extern int aos_api_pppoe_retrieve_config(char*, int*);
/*
 * save current config
 */
extern int aos_api_pppoe_save_config();
/*
 * clear current config
 */
extern int aos_api_pppoe_clear_config();
/*
 * set account username
 */
extern int aos_api_pppoe_username_set(char*);
/*
 * set account password
 */
extern int aos_api_pppoe_password_set(char*);
/*
 * set dns used by dns
 */
extern int aos_api_pppoe_dns_set(char*, char*);

#endif
