/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */
#ifndef AOS_RHC_ROUTER_API_H
#define AOS_RHC_ROUTER_API_H
#include "aosReturnCode.h"

enum
{
	 eAosRc_EntryExist = 117001,
	 eAosRc_EntryNotExist,
	 eAosRc_InvalidRouterEntry,
};

/*
 * add router for a interface
 */
extern int aos_router_add_router(char*, char*, char*, char*, char*);
/*
 *  removes a route entry to the system
 */
extern int aos_router_del_entry(char*);
/*
 * retrieves the system router configuration
 */
extern int aos_router_retrieve_config(char*, int*);
/*
 *  clears the current Router configuration.
 */
extern int aos_router_clear_config();
/*
 * save current Router configuration 
 */
extern int aos_router_save_config();
/*
 * reload Router configuration 
 */
extern int aos_router_load_config();
/*
 * set Router status
 */
extern int aos_router_set_status(int);
#endif
