/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */
#ifndef AOS_RHC_SYSTEMMISC_API_H
#define AOS_RHC_SYSTEMMISC_API_H
#include "aosReturnCode.h"

extern int aos_retrieve_system_info(char*, int*);

extern int aos_system_set_hostname(char*);
#endif
