#ifndef AOS_API_SYSTEMTIME_H
#define AOS_API_SYSTEMTIME_H
/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */
/*
 * set system time
 */
extern int aos_api_system_time_set(int, int, int);
/*
 * show the system time change history log
 */
extern int aos_api_system_time_log_show();
/*
 * set system time zone
 */
extern int aos_api_system_timezone_set(char*);
/*
 * set system time fast  
 */
extern int aos_api_system_time_fast_set(int);
/*
 * set ssytem time slow
 */
extern int aos_api_system_time_slow_set(int);

#endif
