/*
 * generated by genAPI.py
 * author: bill xia<xw_cn@163.com>
 */
#ifndef AOS_RHC_VLAN_API_H
#define AOS_RHC_VLAN_API_H
#include "aosReturnCode.h"

enum
{
	eAosRc_VlanTagAlreadyUsed =115001,
	eAosRc_VlanNoExist,
	//eAosRc_FileNotFound,
	//eAosRc_FileFailRead,
};


/*
 * add vlan
 */
extern int aos_vlan_add(char*, int);
/*
 * remove a vlan tag from interface
 */
extern int aos_vlan_del(char*, int);
/*
 * show vlan config
 */
extern int aos_vlan_retrieve_config(char*, int*);
/*
 * save vlan config
 */
extern int aos_vlan_save_config();
/*
 * load current vlan config
 */
extern int aos_vlan_load_config();
/*
 * clear vlan config
 */
extern int aos_vlan_clear_config();
/*
 * set a vlan tag ip
 */
extern int aos_vlan_add_addr(char*, int, char*);
/*
 * remove a vlan tag ip
 */
extern int aos_vlan_del_addr(char*, int);
/*
 * remove all vlan of a interface
 */
extern int aos_vlan_del_all(char*);
/*
 * remove all vlan ip of a interface
 */
extern int aos_vlan_del_addr_all(char*);
/*
 *  turn on/off the VLAN feature on the attached switch
 */
extern int aos_vlan_switch_set_status(int);
/*
 * add a VLAN tag to a specific port on that switch
 */
extern int aos_vlan_switch_add_vlan(int, int);
/*
 *  set the factory default
 */
extern int aos_vlan_switch_reset();
#endif
