/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package zykie.jimoapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JmoIndexTableType implements org.apache.thrift.TEnum {
  eStrKeyValue(0),
  eIntKeyValue(1),
  eValueOnly(2),
  eCompKey(3),
  eCompKeyValue(4);

  private final int value;

  private JmoIndexTableType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JmoIndexTableType findByValue(int value) { 
    switch (value) {
      case 0:
        return eStrKeyValue;
      case 1:
        return eIntKeyValue;
      case 2:
        return eValueOnly;
      case 3:
        return eCompKey;
      case 4:
        return eCompKeyValue;
      default:
        return null;
    }
  }
}
