/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package zykie.jimoapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JmoIndexQueryResult implements org.apache.thrift.TBase<JmoIndexQueryResult, JmoIndexQueryResult._Fields>, java.io.Serializable, Cloneable, Comparable<JmoIndexQueryResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JmoIndexQueryResult");

  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DOCID_FIELD_DESC = new org.apache.thrift.protocol.TField("docid", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField FOUND_FIELD_DESC = new org.apache.thrift.protocol.TField("found", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField IS_UNIQUE_FIELD_DESC = new org.apache.thrift.protocol.TField("is_unique", org.apache.thrift.protocol.TType.BOOL, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new JmoIndexQueryResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new JmoIndexQueryResultTupleSchemeFactory());
  }

  public String key; // required
  public long docid; // required
  public boolean found; // required
  public boolean is_unique; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KEY((short)1, "key"),
    DOCID((short)2, "docid"),
    FOUND((short)3, "found"),
    IS_UNIQUE((short)4, "is_unique");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KEY
          return KEY;
        case 2: // DOCID
          return DOCID;
        case 3: // FOUND
          return FOUND;
        case 4: // IS_UNIQUE
          return IS_UNIQUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DOCID_ISSET_ID = 0;
  private static final int __FOUND_ISSET_ID = 1;
  private static final int __IS_UNIQUE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DOCID, new org.apache.thrift.meta_data.FieldMetaData("docid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FOUND, new org.apache.thrift.meta_data.FieldMetaData("found", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.IS_UNIQUE, new org.apache.thrift.meta_data.FieldMetaData("is_unique", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JmoIndexQueryResult.class, metaDataMap);
  }

  public JmoIndexQueryResult() {
  }

  public JmoIndexQueryResult(
    String key,
    long docid,
    boolean found,
    boolean is_unique)
  {
    this();
    this.key = key;
    this.docid = docid;
    setDocidIsSet(true);
    this.found = found;
    setFoundIsSet(true);
    this.is_unique = is_unique;
    setIs_uniqueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JmoIndexQueryResult(JmoIndexQueryResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetKey()) {
      this.key = other.key;
    }
    this.docid = other.docid;
    this.found = other.found;
    this.is_unique = other.is_unique;
  }

  public JmoIndexQueryResult deepCopy() {
    return new JmoIndexQueryResult(this);
  }

  @Override
  public void clear() {
    this.key = null;
    setDocidIsSet(false);
    this.docid = 0;
    setFoundIsSet(false);
    this.found = false;
    setIs_uniqueIsSet(false);
    this.is_unique = false;
  }

  public String getKey() {
    return this.key;
  }

  public JmoIndexQueryResult setKey(String key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public long getDocid() {
    return this.docid;
  }

  public JmoIndexQueryResult setDocid(long docid) {
    this.docid = docid;
    setDocidIsSet(true);
    return this;
  }

  public void unsetDocid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DOCID_ISSET_ID);
  }

  /** Returns true if field docid is set (has been assigned a value) and false otherwise */
  public boolean isSetDocid() {
    return EncodingUtils.testBit(__isset_bitfield, __DOCID_ISSET_ID);
  }

  public void setDocidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DOCID_ISSET_ID, value);
  }

  public boolean isFound() {
    return this.found;
  }

  public JmoIndexQueryResult setFound(boolean found) {
    this.found = found;
    setFoundIsSet(true);
    return this;
  }

  public void unsetFound() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FOUND_ISSET_ID);
  }

  /** Returns true if field found is set (has been assigned a value) and false otherwise */
  public boolean isSetFound() {
    return EncodingUtils.testBit(__isset_bitfield, __FOUND_ISSET_ID);
  }

  public void setFoundIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FOUND_ISSET_ID, value);
  }

  public boolean isIs_unique() {
    return this.is_unique;
  }

  public JmoIndexQueryResult setIs_unique(boolean is_unique) {
    this.is_unique = is_unique;
    setIs_uniqueIsSet(true);
    return this;
  }

  public void unsetIs_unique() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IS_UNIQUE_ISSET_ID);
  }

  /** Returns true if field is_unique is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_unique() {
    return EncodingUtils.testBit(__isset_bitfield, __IS_UNIQUE_ISSET_ID);
  }

  public void setIs_uniqueIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IS_UNIQUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((String)value);
      }
      break;

    case DOCID:
      if (value == null) {
        unsetDocid();
      } else {
        setDocid((Long)value);
      }
      break;

    case FOUND:
      if (value == null) {
        unsetFound();
      } else {
        setFound((Boolean)value);
      }
      break;

    case IS_UNIQUE:
      if (value == null) {
        unsetIs_unique();
      } else {
        setIs_unique((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KEY:
      return getKey();

    case DOCID:
      return Long.valueOf(getDocid());

    case FOUND:
      return Boolean.valueOf(isFound());

    case IS_UNIQUE:
      return Boolean.valueOf(isIs_unique());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KEY:
      return isSetKey();
    case DOCID:
      return isSetDocid();
    case FOUND:
      return isSetFound();
    case IS_UNIQUE:
      return isSetIs_unique();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof JmoIndexQueryResult)
      return this.equals((JmoIndexQueryResult)that);
    return false;
  }

  public boolean equals(JmoIndexQueryResult that) {
    if (that == null)
      return false;

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_docid = true;
    boolean that_present_docid = true;
    if (this_present_docid || that_present_docid) {
      if (!(this_present_docid && that_present_docid))
        return false;
      if (this.docid != that.docid)
        return false;
    }

    boolean this_present_found = true;
    boolean that_present_found = true;
    if (this_present_found || that_present_found) {
      if (!(this_present_found && that_present_found))
        return false;
      if (this.found != that.found)
        return false;
    }

    boolean this_present_is_unique = true;
    boolean that_present_is_unique = true;
    if (this_present_is_unique || that_present_is_unique) {
      if (!(this_present_is_unique && that_present_is_unique))
        return false;
      if (this.is_unique != that.is_unique)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(JmoIndexQueryResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKey()).compareTo(other.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, other.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDocid()).compareTo(other.isSetDocid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docid, other.docid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFound()).compareTo(other.isSetFound());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFound()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.found, other.found);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIs_unique()).compareTo(other.isSetIs_unique());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_unique()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_unique, other.is_unique);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("JmoIndexQueryResult(");
    boolean first = true;

    sb.append("key:");
    if (this.key == null) {
      sb.append("null");
    } else {
      sb.append(this.key);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("docid:");
    sb.append(this.docid);
    first = false;
    if (!first) sb.append(", ");
    sb.append("found:");
    sb.append(this.found);
    first = false;
    if (!first) sb.append(", ");
    sb.append("is_unique:");
    sb.append(this.is_unique);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JmoIndexQueryResultStandardSchemeFactory implements SchemeFactory {
    public JmoIndexQueryResultStandardScheme getScheme() {
      return new JmoIndexQueryResultStandardScheme();
    }
  }

  private static class JmoIndexQueryResultStandardScheme extends StandardScheme<JmoIndexQueryResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JmoIndexQueryResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readString();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DOCID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.docid = iprot.readI64();
              struct.setDocidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FOUND
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.found = iprot.readBool();
              struct.setFoundIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IS_UNIQUE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_unique = iprot.readBool();
              struct.setIs_uniqueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JmoIndexQueryResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        oprot.writeString(struct.key);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DOCID_FIELD_DESC);
      oprot.writeI64(struct.docid);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(FOUND_FIELD_DESC);
      oprot.writeBool(struct.found);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(IS_UNIQUE_FIELD_DESC);
      oprot.writeBool(struct.is_unique);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JmoIndexQueryResultTupleSchemeFactory implements SchemeFactory {
    public JmoIndexQueryResultTupleScheme getScheme() {
      return new JmoIndexQueryResultTupleScheme();
    }
  }

  private static class JmoIndexQueryResultTupleScheme extends TupleScheme<JmoIndexQueryResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JmoIndexQueryResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetKey()) {
        optionals.set(0);
      }
      if (struct.isSetDocid()) {
        optionals.set(1);
      }
      if (struct.isSetFound()) {
        optionals.set(2);
      }
      if (struct.isSetIs_unique()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetKey()) {
        oprot.writeString(struct.key);
      }
      if (struct.isSetDocid()) {
        oprot.writeI64(struct.docid);
      }
      if (struct.isSetFound()) {
        oprot.writeBool(struct.found);
      }
      if (struct.isSetIs_unique()) {
        oprot.writeBool(struct.is_unique);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JmoIndexQueryResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.key = iprot.readString();
        struct.setKeyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.docid = iprot.readI64();
        struct.setDocidIsSet(true);
      }
      if (incoming.get(2)) {
        struct.found = iprot.readBool();
        struct.setFoundIsSet(true);
      }
      if (incoming.get(3)) {
        struct.is_unique = iprot.readBool();
        struct.setIs_uniqueIsSet(true);
      }
    }
  }

}

