/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package zykie.jimoapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JmoJQLDocType implements org.apache.thrift.TEnum {
  eInvalid(0),
  eTableDoc(1),
  eIndexDoc(2),
  eSchemaDoc(3),
  eDatasetDoc(4),
  eJobDoc(5),
  eTaskDoc(6),
  eDataProcDoc(7),
  eDataScannerDoc(8),
  eDataConnectorDoc(9),
  eDataRecordDoc(10),
  eDataFieldDoc(11),
  eDatabaseDoc(12),
  eMap(13),
  eVirtualField(14),
  eServiceDoc(15),
  eStatisticsDoc(16),
  eDocMax(17);

  private final int value;

  private JmoJQLDocType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JmoJQLDocType findByValue(int value) { 
    switch (value) {
      case 0:
        return eInvalid;
      case 1:
        return eTableDoc;
      case 2:
        return eIndexDoc;
      case 3:
        return eSchemaDoc;
      case 4:
        return eDatasetDoc;
      case 5:
        return eJobDoc;
      case 6:
        return eTaskDoc;
      case 7:
        return eDataProcDoc;
      case 8:
        return eDataScannerDoc;
      case 9:
        return eDataConnectorDoc;
      case 10:
        return eDataRecordDoc;
      case 11:
        return eDataFieldDoc;
      case 12:
        return eDatabaseDoc;
      case 13:
        return eMap;
      case 14:
        return eVirtualField;
      case 15:
        return eServiceDoc;
      case 16:
        return eStatisticsDoc;
      case 17:
        return eDocMax;
      default:
        return null;
    }
  }
}
