////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
//   
//
// Modification History:
// 2014/12/06 Created by Chen Ding
////////////////////////////////////////////////////////////////////////////
#ifndef Aos_JimoAPI_JimoFunc_h
#define Aos_JimoAPI_JimoFunc_h


class JimoFunc
{
public:
	enum E
	{
		eInvalid,

		eMethodGetCubeEndpointIDs,

		// HelloWorld Package
		eJimoCallSyncNorm,
		eJimoCallSyncRead,
		eJimoCallSyncWrite,
		eJimoCallAsyncNorm,
		eJimoCallAsyncRead,
		eJimoCallAsyncWrite,
		
		// Doc Package
		eGetDocByName,
		eAddReq,
		eAppendBinaryDoc,
		eBatchDataReceived,
		eBatchGetDocs,
		eBindCloudid_Doc,   
		eBindObjid_Doc,
		eCreateDoc,
		eCreateDoc1,
		eCreateDocSafe1,
		eCreateDocSafe3,
		eCreateBinaryDoc,
		eCreateBinaryDocByVid,
		eCreateJQLTable,	
		eCreateDocByJQL, 
		eCreateSnapshot_Doc,
		eCommitSnapshot_Doc,
		eCreateRootCtnr,
		eCreateDocByTemplate1,
		eCloneDoc,
		eDoesObjidExist,
		eDeleteBinaryDocByObjid,
		eDeleteBinaryDocByDocid,
		eDeleteObj,
		eDropJQLTable, 
		eDeleteDocByDocid,	
		eDeleteDocByObjid,
		eDeleteDoc,
		eGetAccessRcd,
		eGetDoc,
		eGetDocByFlag,
		eGetDocidByCloudid_Doc,
		eGetDocByObjid,
		eGetDocidByObjid_Doc,
		eGetDocByU64Docid,
		eGetDocByStrDocid,
		eGetDocByCloudid,
		eGetUserAcct,
		eGetDeletedDoc,
		eGetObjidByDocid,
		eGetCloudid,
		eGetAccessRecord,
		eGetParentContainer,
		eGetTableNames,
		eGetJQLDocs,
		eGetJQLDocidByTablename,
		eGetDocByJQL,	
		eGetParentContainerByObjid,	
		eGetParentContainerByDocid,	
		eGetDocByKey1,
		eGetDocByKey2,
		eGetDocByKeys,
		eIsCloudidBound,
		eIsShowLog,
		eIncrementValue,
		eIsLog,
		eIsRepairing,
		eModifyAttrStr1,
		eModifyAttrStr,
		eModifyAttrU64,
		eModifyAttrXPath,
		eModifyBinaryDocByStat,
		eModifyObj,
		eModifyObjAdd,
		eMergeSnapshot_Doc,
		eProcDocLock,
		eProcNotifyMsg,
		ePurgeDocByObjid,
		ePurgeDocBydocid,
		ePurgeDocByCloudid,
		eWriteLockDoc,
		eWriteLockDocByTime,
		eWriteUnlockDocByDocid,
		eWriteLockDocByObjid,
		eWriteAccessDoc,
		eReleaseWriteLock,
		eReleaseWriteLockDocByObjid,
		eReleaseWriteLockDocByDocid,
		eRetrieveBinaryDocByStat,
		eRetrieveBinaryDocByObjid,
		eRetrieveBinaryDocByDocid,
		eRetrieveBinaryDocByCaller,
		eRollbackSnapshot,
		eReadLockDocByDocid,
		eReadUnlockDocByDocid,

		// IIL Package
		eGetDocidByObjid,
		eBindObjid,
		eUnBindObjid,
		eAddStrValueDocByID,
		eAddStrValueDocByName,
		eRemoveStrValueDocByID,
		eRemoveStrValueDocByName,
		eAddU64ValueDocByID,
		eAddU64ValueDocByName,
		eRemoveU64ValueDocByID,
		eRemoveU64ValueDocByName,
		eGetDocidBySiteidObjid,
		eIncrementKeyedValue,
		eGetDocidByIILIDOpr,
		eGetDocidByIILNameOpr,
		eGetDocidByIILIDDft,
		eGetDocidByIILNameDft,
		eBindCloudid,
		eUnBindCloudid,
		eReBindCloudid,
		eIncrementDocidToTable,
		eIncrementInlineSearchValue,
		eGetDocidByCloudid,
		eGetCtnrMemDocidByOneKey,
		eGetCtnrMemDocidByTwoKey,
		eAddHitDoc,
		eNextId1,
		eAddU64ValueDocToTableByID,
		ePreQuerySafeByIILName,
		ePreQuerySafeByIILID,
		eQuerySafeByIILName,
		eRemoveHitDoc,
		eAddHitDocByTrans,
		eAddStrValueDocByTrans,
		eAddStrValueDocToTable,
		eAddU64ValueDocByTrans,
		eRemoveHitDocByTrans,
		eRemoveStrValueDocByIDTrans,
		eRemoveStrValueDocByNameTrans,
		eRemoveU64ValueDocByIDTrans,
		eRemoveU64ValueDocByNameTrans,
		eRemoveU64DocByIDValue,
		eRemoveU64DocByNameValue,
		eModifyStrValueDocByID,
		eModifyStrValueDocByName,
		eGetIILID,
		eCounterRangeByID,
		eCounterRangeByName,
		eRebuildBitmap,
		eQuerySafeByIILID,
		eQuerySafeByNameSnap,
		eCreateTablePublicByID,
		eCreateTablePublicByIDName,
		eSetU64ValueDocUnique,
		eSetU64ValueDocUniqueToTable,
		eSetStrValueDocUnique,
		eSetStrValueDocUniqueToTable,
		eIncrementDocidStrByID,
		eIncrementDocidStrByName,
		eIncrementDocidU64ByID,
		eIncrementDocidU64ByName,
		eCreateIILPublicByID,
		eCreateIILPublicByIDName,
		eGetDocidsByKeysIILID,
		eGetDocidsByKeysIILName,
		eDeleteIILByID,
		eDeleteIILByName,
		eGetSplitValue,
		eResetKeyedValue,
		eStrBatchAdd,
		eStrBatchDel,
		eStrBatchInc,
		eMergeSnapshot,
		eCreateSnapshot,
		eCommitSnapshot,
		eRollBackSnapshot,
		eGetTotalNumDocsByName,
		eGetTotalNumDocsByIDName,
		eStrBatchAddMerge,
		eStrBatchIncMerge,
		eHitBatchAdd,
		eU64BatchAdd,
		eJimoTableBatchAdd,
		eQuerySafeByNameOpr,
		eQuerySafeByIDOpr,
		eRebindObjid,
		eBitmapQueryNewSafe,
		eBitmapRsltQuerySafe,
		eMoveManualOrder,
		eRemoveManualOrder,
		eSwapManualOrder,
		eAppendManualOrder,
		eGetDocids,
		eAddInlineSearchValue,
		eModifyInlineSearchValue,
		eRemoveInlineSearchValue,
		eGetBatchDocids,
		eUpdateKeyedValue,
		eRemoveStrFirstValueDoc,
		eAddU64ValueDocToTableByName,

		// SysAdmin Package
		eFlushOutput,			// Ice/Xia Fan, 2015/02/03
		eMethodGetIDO,

		// Raft package   Phil 2015-05-11
		eRaftSendMsg,
		eRaftRecvMsg,

		eLastEntry
	};
};

#endif
