#!/bin/sh
set -e
if [ `id -u` -ne 0 ]; then
	echo "You need root privileges to run this script"
	exit 1
fi
NAME="jimod"
DESC="JimoDb Agent Server"
PIDFILE="/var/run/$NAME.pid"
AGENTSERVER_PATH="/usr/sbin/jimod"
. /lib/lsb/init-functions

JIMOD_CONFIG="jimod_config"
JIMO_DIR="/etc/jimo"
JIMOD_OPTS="-c $JIMO_DIR/$JIMOD_CONFIG"

case "$1" in
	start)
	log_daemon_msg "Starting $DESC : $NAME" || true
	if start-stop-daemon --start --background --quiet --oknodo --pidfile $PIDFILE -m --exec $AGENTSERVER_PATH -- $JIMOD_OPTS; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
	fi
		;;
	stop)
		log_daemon_msg "Stopping $DESC : $NAME" || true
		if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
			log_end_msg 0 || true
		else
			log_end_msg 1 || true
		fi
		if [ -e $PIDFILE ]; then
			rm $PIDFILE
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
	log_action_msg "Usage: {start|stop|restart}" || true
	exit 1	
esac

exit 0
