/*generated by gencode.py
 *author: bill xia
 */

#include <stdio.h>
#include "wan.h"
#include <iostream.h>

int main(int argc,char **argv)
{
	char result[10240];
	int ret = 0;
	int len = 10240;
	int total_case = 0;
	int fail_case = 0;
	int index=1;
	int count=0;
	int maxruntime=2;
	FILE *fp=NULL; 

	while(index<argc)
	{
		if(strcmp(argv[index],"-t")==0)
		{
			maxruntime=atoi(argv[++index]);
			index++;
			continue;
		}
		if(strcmp(argv[index],"-h")==0)
		{
			cout<<"----------------------helps for usage------------------------------------------"<<endl;
			cout<<"1 usage: ./wantester [-t [count]]"<<endl;
			cout<<""<<endl;
			cout<<"2 the parameter [-t [count]] is optinal,it control the total run count of this application ."<<endl;
			cout<<" it's default value is 2 ,if it need to set it .it need a number of 2's times(eg: 2,4,6,...)  "<<endl;
			cout<<""<<endl;
			cout<<"3 the result will be added to the files wanresult1 and wanresult2 in the current directory at the mean time"<<endl;
			cout<<" ,and this two result file's content should be the same"<<endl;
			cout<<""<<endl;
			cout<<"4 exmaple: './wantester -t 10 ' or ' ./wantester '"<<endl;
			cout<<""<<endl;
			exit(0);
		}
	}



	while(count<maxruntime)
	{
		printf("================================ Now run the %d time=========================================\n",count+1);
		printf("==============================================================================================\n");

		if(count%2==0)
		{
			fp=fopen("wanresult1","a+");
		}
		else
		{
			fp=fopen("wanresult2","a+");
		}  


		cout<<"====================================== section1: get ip by dhcp method ================================================="<<endl;
		len = 10240;
		ret = aos_wan_get_addr(result, &len);
		if (ret != 0) {
			printf("caseId:2	ret = %d	Error\n", ret);
			fail_case++;
		}
		printf("%s\n", result);
		total_case++;
		cout<<"wan  ip address  show ret= "<<ret<<endl;
		fprintf(fp,"wan  ip address  show ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_method("dhcp");
		if (ret != 0) {
			printf("caseId:3	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan connect method set ret= "<<ret<<endl;
		fprintf(fp,"wan connect method set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_wan_set_hc_interval(4);
		if (ret != 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check time set ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check time set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_remote_ip("172.22.0.1");
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check  set ip ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check set ip ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_dns_set("1.1.1.1", "2.2.2.2");
		if (ret != 0) {
			printf("caseId:8	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan dns set ret= "<<ret<<endl;
		fprintf(fp,"wan dns set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_save_config();
		if (ret != 0) {
			printf("caseId:12	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan save config ret= "<<ret<<endl;
		fprintf(fp,"wan save config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_clear_config();
		if (ret != 0) {
			printf("caseId:11	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan clear config ret= "<<ret<<endl;
		fprintf(fp,"wan clear config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		cout<<"====================================== section2: get ip by static method ================================================="<<endl;
		len = 10240;
		ret = aos_wan_get_addr(result, &len);
		if (ret != 0) {
			printf("caseId:2	ret = %d	Error\n", ret);
			fail_case++;
		}
		printf("%s\n", result);
		total_case++;
		cout<<"wan  ip address  show ret= "<<ret<<endl;
		fprintf(fp,"wan  ip address  show ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_method("static");
		if (ret != 0) {
			printf("caseId:3	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan connect method set ret= "<<ret<<endl;
		fprintf(fp,"wan connect method set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_addr("172.22.111.107", "255.255.0.0");
		if (ret != 0) {
			printf("caseId:1	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan ip address set ret= "<<ret<<endl;
		fprintf(fp,"wan ip address set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_hc_interval(1);
		if (ret != 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check time set ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check time set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_remote_ip("172.22.2.2");
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check  set ip ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check set ip ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_dns_set("1.2.3.4", "5.6.7.8");
		if (ret != 0) {
			printf("caseId:8	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan dns set ret= "<<ret<<endl;
		fprintf(fp,"wan dns set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_save_config();
		if (ret != 0) {
			printf("caseId:12	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan save config ret= "<<ret<<endl;
		fprintf(fp,"wan save config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_wan_clear_config();
		if (ret != 0) {
			printf("caseId:11	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan clear config ret= "<<ret<<endl;
		fprintf(fp,"wan clear config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;




		cout<<"====================================== section3: get ip by adsl method ================================================="<<endl;
		len = 10240;
		ret = aos_wan_get_addr(result, &len);
		if (ret != 0) {
			printf("caseId:2	ret = %d	Error\n", ret);
			fail_case++;
		}
		printf("%s\n", result);
		total_case++;
		cout<<"wan  ip address  show ret= "<<ret<<endl;
		fprintf(fp,"wan  ip address  show ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		/*
		   ret = aos_wan_set_method("adsl");
		   if (ret != 0) {
		   printf("caseId:3	ret = %d	Error\n", ret);
		   fail_case++;
		   }
		   total_case++;
		   cout<<"wan connect method set ret= "<<ret<<endl;
		   fprintf(fp,"wan connect method set ret=%d\n", ret);
		   cout<<"-----------------------------------------------------------------------------------------------"<<endl;
		   */   

		ret = aos_wan_set_hc_interval(2);
		if (ret != 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check time set ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check time set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_remote_ip("172.22.2.2");
		if (ret != 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check  set ip ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check set ip ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_wan_set_adsl_user("hiadfdfdfd");
		if (ret != 0) {
			printf("caseId:6	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan adsl username set ret= "<<ret<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_adsl_password("passwordadsl");
		if (ret != 0) {
			printf("caseId:7	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan adsl  password set ret= "<<ret<<endl;
		fprintf(fp,"wan adsl password set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_dns_set("72.134.3.1", "192.169.1.1");
		if (ret != 0) {
			printf("caseId:8	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan dns set ret= "<<ret<<endl;
		fprintf(fp,"wan dns set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan show config set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_save_config();
		if (ret != 0) {
			printf("caseId:12	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan save config ret= "<<ret<<endl;
		fprintf(fp,"wan save config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		ret = aos_wan_clear_config();
		if (ret != 0) {
			printf("caseId:11	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan clear config ret= "<<ret<<endl;
		fprintf(fp,"wan clear config set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;

		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan show config set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		cout<<"====================================== section4: wrong inputs  ================================================="<<endl;

		len = 102;
		ret = aos_wan_get_addr(result, &len);
		if (ret == 0) {
			printf("caseId:2	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan  ip address  show ret= "<<ret<<endl;
		fprintf(fp,"wan  ip address  show ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_method("adsll");
		if (ret == 0) {
			printf("caseId:3	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan connect method set ret= "<<ret<<endl;
		fprintf(fp,"wan connect method set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_wan_set_hc_interval(.2);
		if (ret == 0) {
			printf("caseId:4	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check time set ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check time set ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_remote_ip("172.22.2..2");
		if (ret == 0) {
			printf("caseId:5	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan healthy check  set ip ret= "<<ret<<endl;
		fprintf(fp,"wan healthy check set ip ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		ret = aos_wan_set_adsl_user(" ");
		if (ret == 0) {
			printf("caseId:6	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan adsl username set ret= "<<ret<<endl;
		fprintf(fp,"wan adsl username set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_set_adsl_password(" ");
		if (ret == 0) {
			printf("caseId:7	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan adsl  password set ret= "<<ret<<endl;
		fprintf(fp,"wan adsl password set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;



		ret = aos_wan_dns_set("72.134.3.341", "192.169.1.1");
		if (ret == 0) {
			printf("caseId:8	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan dns set ret= "<<ret<<endl;
		fprintf(fp,"wan dns set  ret=%d\n", ret);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;







		len = 10240;
		ret = aos_wan_retrieve_config(result, &len);
		if (ret != 0) {
			printf("caseId:10	ret = %d	Error\n", ret);
			fail_case++;
		}
		total_case++;
		cout<<"wan show config ret= "<<ret<<"\n"<<result<<endl;
		fprintf(fp,"wan show config set  ret=%d\n%s\n", ret,result);
		cout<<"-----------------------------------------------------------------------------------------------"<<endl;


		/*
		   ret = aos_wan_load_config();
		   if (ret != 0) {
		   printf("caseId:13	ret = %d	Error\n", ret);
		   fail_case++;
		   }
		   total_case++;
		   */
		fclose(fp);
		count++;
	}

	cout<<"================================= WAN APIS RUN RESULT SUMMARY==================================== "<<endl;
	printf("the run total count is: %d\n ",count);
	printf("total case: %d\n fail case:%d\n", total_case, fail_case);
	//printf(" the differdence between the result files is: \n", system(" diff wanresult1 wanresult2"));

	cout<<""<<endl;
	cout<<"=================================================================================================== "<<endl;
	return 0;
}
