/*generated by gencode.py
 *author: bill xia
 */

#include <stdio.h>
#include "vlan.h"

int main()
{
    char result[10240];
    int ret	=0;
    int len	= 10240;
    int total_case = 0;
    int fail_case = 0;

    ret = aos_vlan_add("outcard", 3);
    if (ret != 0) {
        printf("caseId:1	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_add("incard", 3);
    if (ret != 0) {
        printf("caseId:2	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_del("incard", 3);
    if (ret != 0) {
        printf("caseId:3	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_retrieve_config(result, &len);
    if (ret != 0) {
        printf("caseId:4	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_save_config();
    if (ret != 0) {
        printf("caseId:5	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

//not use 
/*
    ret = aos_router_load_config();
    if (ret != 0) {
        printf("caseId:6	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;
*/
/*
    ret = aos_vlan_clear_config();
    if (ret != 0) {
        printf("caseId:7	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;
*/

    ret = aos_vlan_add_addr("outcard", 3, "192.168.0.1");
    if (ret != 0) {
        printf("caseId:8	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_del_addr("outcard", 3);
    if (ret != 0) {
        printf("caseId:9	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_del_all("incard");
    if (ret != 0) {
        printf("caseId:10	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_del_addr_all("incard");
    if (ret != 0) {
        printf("caseId:11	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_del_addr_all("outcard");
    if (ret != 0) {
        printf("caseId:12	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_switch_set_status(0);
    if (ret != 0) {
        printf("caseId:13	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_switch_add_vlan(1, 12);
    if (ret != 0) {
        printf("caseId:14	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;


    ret = aos_vlan_switch_reset();
    if (ret != 0) {
        printf("caseId:15	ret = %d	Error\n", ret);
        fail_case++;
    }
    total_case++;

    printf("total case: %d\n fail case:%d", total_case, fail_case);
    return 0;
}
