//////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005
// Packet Engineering, Inc. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification is not permitted unless authorized in writing by a duly
// appointed officer of Packet Engineering, Inc. or its derivatives
//
// Description:
// This file is automatically generated by the TorturerGen facility. 
//
// Modification History:
// 4/21/2007 Created by TorturerGen Facility
//////////////////////////////////////////////////////////////////////////
#ifndef Aos_HacDaemon_Tester_AosHacCliTester_h
#define Aos_HacDaemon_Tester_AosHacCliTester_h

#include "Debug/Debug.h"
#include "StreamSimu/StreamType.h"
#include "Tester/TestPkg.h"
#include "Util/Ptrs.h"



class AosHacCliTester : public OmnTestPkg
{
private:
    int              mBasicTestRepeat;
    AosGenTablePtr   mTable;

public:
    AosHacCliTester();
    ~AosHacCliTester();

    virtual bool     start();

	bool	config();
	bool	getUser(bool &correct, 
					const AosStreamType::E app, 
					OmnString &user); 
	bool	getPasswd(const bool correct, 
					const OmnString &user, 
					OmnString &passwd); 
	bool	getSendIP(const bool correct,
					const OmnString &user, 
					const AosStreamType::E app,
					OmnIpAddr &sendIP);
	bool	getRecvIPPort(const bool correct, 
					const AosStreamType::E app,
					const OmnString &user,
					OmnIpAddr &recvIP, 
					int &recvPort);

private:
    bool basicTest(const u32 repeat, const AosGenTablePtr &table);
};
#endif

